swagger: "2.0"
info:
  version: "0.0.1"
  title: SendLove I/O
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /swagger:
    x-swagger-pipe: swagger_raw
    # what is this?
  /thing:
    # binds a127 app logic to a route
    x-swagger-router-controller: thingController
    get:
      description: Returns a list of things
      # used as the method name of the controller
      operationId: getThing
      parameters:
        - name: geocode
          in: query
          description: Latitude and longitude of a thing.
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ThingResponse"
        # responses may fall through to errors
        default:
          description: Thing Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /part:
    # binds a127 app logic to a route
    x-swagger-router-controller: partController
    get:
      description: Returns a list of parts
      # used as the method name of the controller
      operationId: getPart
      parameters:
        - name: title
          in: query
          description: The name or short description of a part.
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/PartResponse"
        # responses may fall through to errors
        default:
          description: Part Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ThingResponse:
    required:
      - message
    properties:
      message:
        type: string
  PartResponse:
    required:
      - message
    properties:
      message:
        type: string

